### ISSUE TITLE
Error after login displayed

### ISSUE THREAD

**Issue by FelixReuthlinger** [Tercioo/Plater-Nameplates-Classic#7]
Note: I moved this issue from https://github.com/Tercioo/Plater-Nameplates/issues/64 to here, since it might be more classic related.

For quite some time now I got this error when logging in with any char and having Plater (latest version) installed and acitve:

---
Message: Interface\AddOns\Plater\Plater-Plater-1.13.5.91-Classic.lua:8031: attempt to call method 'RemoveRule' (a nil value)
Time: Mon Oct 12 08:23:13 2020
Count: 1
Stack: Interface\AddOns\Plater\Plater-Plater-1.13.5.91-Classic.lua:8031: attempt to call method 'RemoveRule' (a nil value)

Locals:

---

I though maybe this gonna be resolved some time, but maybe noone being aware about this?

I also update the version with Twitch, so should be latest.
![image](https://user-images.githubusercontent.com/10428747/95764521-db6c0900-0cb0-11eb-8506-5bb6e916e0ba.png)

Additionally I am also using WeakAuras and the companion App to update things, so even that should update everything fine.

**Comment by cont1nuity** [comment]
My bad, not Masque but OmniCC is the culprit here. You have an outdated version active.

**Comment by FelixReuthlinger** [comment]
Ok, thx for the hint. The funny thing is, I didn't actively install OmniCC at all. 
Now after I installed it, the error disappeared. 
So, thx. I guess this could be resolved then, right?

**Comment by cont1nuity** [comment]
Yes. It seems some other addon you use has an outdated version packaged then...
